project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
  resources: 
    - "google77fcea9ec5fbdd3b.html"

website:
  title: "Davidson DataFest"
  description: "48-hour data science hackathon at Davidson College!"
  site-url: https://datasci.davidson.edu/datafest
  repo-url: https://github.com/DavidsonCollege-DataScience/datafest
  open-graph: true # https://quarto.org/docs/websites/website-tools.html#open-graph
  favicon: img/Circle-favicon-32x32.png
  page-footer: 
    center: |
      [![](img/davidson-wordmark-horizontal-lockup-white_sm.png){fig-alt="Davidson College" target="_blank" width="50%"}](https://davidson.edu)
    right: "Made with Quarto" 
    background: "#0f1012"
    foreground: "#ffffff"
  # announcement: 
  #   icon: info-circle
  #   dismissable: false
  #   content: "Early registration for DataFest is open until March 1!"
  #   type: dark
  #   position: below-navbar
    
  navbar:
    search: false
    right:
      - text: "<span class='btn btn-light'>Register now!</span>"
        href: https://forms.gle/tCDkfefZRxTFJRH79
      - text: About
        href: index.qmd#about
      - text: Location
        href: index.qmd#location
      - text: Schedule
        href: index.qmd#schedule
      - text: FAQ
        href: index.qmd#faq
      - text: Sponsors
        href: index.qmd#sponsors
      - text: Blog
        href: index.qmd#blog
      # - icon: rss
      #   href: index.xml
    # tools:
    #   - icon: github
    #     href: https://github.com/DavidsonCollege-DataScience/datafest
    #     target: _blank

format:
  html:
    backgroundcolor: "#e6e6e6" 
    fontcolor: "black"
    linkcolor: "black"
    mainfont: "Atkinson Hyperlegible"
    fontsize: 20px
    theme: [materia, styles.scss]
    
